CREATE TABLE "cart" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cart_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"customer_id" integer NOT NULL,
	"restaurant_id" integer NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "order_status_history" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "order_status_history_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"order_id" integer NOT NULL,
	"status" "order_status" NOT NULL,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "cart_items" DROP CONSTRAINT "cart_items_customer_id_users_id_fk";
--> statement-breakpoint
ALTER TABLE "cart_items" DROP CONSTRAINT "cart_items_restaurant_id_restaurants_id_fk";
--> statement-breakpoint
DROP INDEX "unique_cart_item";--> statement-breakpoint
ALTER TABLE "cart_items" ADD COLUMN "cart_id" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "deliveries" ADD COLUMN "picked_at" timestamp;--> statement-breakpoint
ALTER TABLE "deliveries" ADD COLUMN "delivered_at" timestamp;--> statement-breakpoint
ALTER TABLE "menu_items" ADD COLUMN "is_available" boolean DEFAULT true;--> statement-breakpoint
ALTER TABLE "order_items" ADD COLUMN "total_price" numeric(10, 2) NOT NULL;--> statement-breakpoint
ALTER TABLE "orders" ADD COLUMN "subtotal" numeric(10, 2) NOT NULL;--> statement-breakpoint
ALTER TABLE "orders" ADD COLUMN "delivery_fee" numeric(10, 2) DEFAULT '0';--> statement-breakpoint
ALTER TABLE "orders" ADD COLUMN "tax" numeric(10, 2) DEFAULT '0';--> statement-breakpoint
ALTER TABLE "orders" ADD COLUMN "discount" numeric(10, 2) DEFAULT '0';--> statement-breakpoint
ALTER TABLE "orders" ADD COLUMN "address_id" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "payments" ADD COLUMN "payment_provider_id" varchar(255);--> statement-breakpoint
ALTER TABLE "payments" ADD COLUMN "transaction_id" varchar(255);--> statement-breakpoint
ALTER TABLE "restaurants" ADD COLUMN "is_open" boolean DEFAULT true;--> statement-breakpoint
ALTER TABLE "restaurants" ADD COLUMN "is_active" boolean DEFAULT true;--> statement-breakpoint
ALTER TABLE "restaurants" ADD COLUMN "delivery_time" integer;--> statement-breakpoint
ALTER TABLE "restaurants" ADD COLUMN "delivery_fee" numeric(10, 2) DEFAULT '0';--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "is_verified" boolean DEFAULT false;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "is_active" boolean DEFAULT true;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "profile_image" varchar(255);--> statement-breakpoint
ALTER TABLE "cart" ADD CONSTRAINT "cart_customer_id_users_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cart" ADD CONSTRAINT "cart_restaurant_id_restaurants_id_fk" FOREIGN KEY ("restaurant_id") REFERENCES "public"."restaurants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "order_status_history" ADD CONSTRAINT "order_status_history_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "unique_user_cart" ON "cart" USING btree ("customer_id");--> statement-breakpoint
ALTER TABLE "cart_items" ADD CONSTRAINT "cart_items_cart_id_cart_id_fk" FOREIGN KEY ("cart_id") REFERENCES "public"."cart"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_address_id_address_id_fk" FOREIGN KEY ("address_id") REFERENCES "public"."address"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "user_default_address" ON "address" USING btree ("user_id") WHERE "address"."is_default" = $1;--> statement-breakpoint
CREATE UNIQUE INDEX "unique_category" ON "categories" USING btree ("name");--> statement-breakpoint
CREATE UNIQUE INDEX "unique_menu_category" ON "menu_item_categories" USING btree ("menu_item_id","category_id");--> statement-breakpoint
CREATE UNIQUE INDEX "unique_restaurant_category" ON "restaurant_categories" USING btree ("restaurant_id","category_id");--> statement-breakpoint
CREATE UNIQUE INDEX "unique_cart_item" ON "cart_items" USING btree ("cart_id","menu_item_id");--> statement-breakpoint
ALTER TABLE "cart_items" DROP COLUMN "customer_id";--> statement-breakpoint
ALTER TABLE "cart_items" DROP COLUMN "restaurant_id";--> statement-breakpoint
ALTER TABLE "reviews" ADD CONSTRAINT "rating_check" CHECK (rating BETWEEN 1 AND 5);